'use client';
import { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { Kelas, Siswa, StatusPresensi } from '@/lib/types';
import { today } from '@/lib/utils';
const statuses: StatusPresensi[] = ['hadir','izin','sakit','alpa'];
const labels = { hadir: 'Hadir', izin: 'Izin', sakit: 'Sakit', alpa: 'Alpa' };
export function PresensiForm() { const [kelas,setKelas]=useState<Kelas[]>([]),[classId,setClassId]=useState(''),[date,setDate]=useState(today()),[students,setStudents]=useState<Siswa[]>([]),[attendance,setAttendance]=useState<Record<string,StatusPresensi>>({}),[subject,setSubject]=useState(''),[material,setMaterial]=useState(''),[issue,setIssue]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{supabase.from('kelas').select('*').order('nama').then(({data})=>setKelas(data??[]))},[]); useEffect(()=>{if(!classId)return; Promise.all([supabase.from('siswa').select('*').eq('kelas_id',classId).order('nama'),supabase.from('presensi').select('*').eq('kelas_id',classId).eq('tanggal',date),supabase.from('jurnal_mengajar').select('*').eq('kelas_id',classId).eq('tanggal',date).maybeSingle()]).then(([s,p,j])=>{setStudents(s.data??[]); const next:Record<string,StatusPresensi>={}; (s.data??[]).forEach(x=>next[x.id]=(p.data??[]).find(q=>q.siswa_id===x.id)?.status ?? 'hadir'); setAttendance(next); setSubject(j.data?.mata_pelajaran??'');setMaterial(j.data?.materi??'');setIssue(j.data?.kendala??'')})},[classId,date]);
 const save=async()=>{if(!classId||!students.length){setMessage('Pilih kelas yang memiliki siswa.');return} if(!subject||!material){setMessage('Mata pelajaran dan materi wajib diisi.');return} setSaving(true); const rows=students.map(s=>({siswa_id:s.id,kelas_id:classId,tanggal:date,status:attendance[s.id]||'hadir'})); const {error}=await supabase.from('presensi').upsert(rows,{onConflict:'siswa_id,tanggal'}); if(!error) await supabase.from('jurnal_mengajar').upsert({kelas_id:classId,tanggal:date,mata_pelajaran:subject,materi:material,kendala:issue||null},{onConflict:'kelas_id,tanggal'}); setSaving(false);setMessage(error?'Gagal menyimpan presensi.':'Presensi dan jurnal berhasil disimpan.'); };
 return <div className="space-y-6"><section className="card p-5"><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Kelas</label><select className="input" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Pilih kelas</option>{kelas.map(k=><option key={k.id} value={k.id}>{k.nama}</option>)}</select></div><div><label className="label">Tanggal</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div></section>{classId&&<><section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Kehadiran Siswa</h2><p className="text-sm text-slate-500">Pilih status setiap siswa.</p></div><div className="divide-y">{students.map((s,i)=><div key={s.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><span className="mr-3 text-sm text-slate-400">{i+1}</span><b>{s.nama}</b><span className="ml-2 text-xs text-slate-400">{s.nis}</span></div><div className="grid grid-cols-4 gap-1 rounded-lg bg-sky-100 p-1">{statuses.map(status=><button key={status} onClick={()=>setAttendance({...attendance,[s.id]:status})} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${attendance[s.id]===status?'bg-white text-brand-700 shadow-sm':'text-slate-500'}`}>{labels[status]}</button>)}</div></div>)}{!students.length&&<p className="p-8 text-center text-slate-400">Kelas ini belum memiliki siswa.</p>}</div></section><section className="card p-5"><h2 className="font-bold">Jurnal Mengajar</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><label className="label">Mata Pelajaran</label><input className="input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Contoh: Matematika"/></div><div><label className="label">Bab / Materi</label><input className="input" value={material} onChange={e=>setMaterial(e.target.value)} placeholder="Contoh: Pecahan"/></div><div className="sm:col-span-2"><label className="label">Kendala Kelas (opsional)</label><textarea className="input min-h-24" value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Catatan kegiatan atau kendala..."/></div></div></section><div className="flex items-center gap-4"><button onClick={save} disabled={saving} className="btn-primary"><Save size={17}/>{saving?'Menyimpan...':'Simpan Presensi'}</button>{message&&<span className="text-sm text-slate-600">{message}</span>}</div></>}</div> }
